import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import SessionProviders from "./utils/provider/SessionProviders";
import NavigationRail from "./component/common/NavigationRail";
import RQProvider from "./utils/provider/RQProvider";

const inter = Noto_Sans_KR({ preload: false, weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-surface`}>
        <SessionProviders>
          <RQProvider>
            <NavigationRail />
            {children}
          </RQProvider>
        </SessionProviders>
      </body>
    </html>
  );
}
